AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  Syncline application stack

Globals:
  Function:
    Timeout: 3

Resources:
  SyncLineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ma-hackathon-syncline
      MemorySize: 5120
      Timeout: 900
      Policies:
        - SecretsManagerReadWrite
        - AWSLambdaBasicExecutionRole
      CodeUri: ./src
      Handler: lambda-handler.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        MyAPI:
          Type: Api
          Properties:
            Path: /test
            Method: get
            RestApiId: 
              Ref: MyApiGateway

  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,OPTIONS'"
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: AWS::StackName
        paths:
          /test:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub:
                  - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
                  - LambdaArn: !GetAtt SyncLineFunction.Arn