name: Push Text File Test

on:
  push:
    branches:
      - main
    paths:
      - 'Team04/**'

jobs:
  compare-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install git
        run: sudo apt-get install git -y

      - name: find differences
        run: |
          git diff HEAD^ HEAD > diff.txt

      - name: Get differences between branches
        id: diff
        run: |
          git fetch origin main
          git diff --name-status origin/main ${GITHUB_REF} > differences.txt || echo "No differences found"

      - name: Display differences
        run: cat diff.txt

      - name: Commit and push changes
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add diff.txt
          git commit -m "Add differences between branches"
          git push