name: Push Text File Test

on:
  push:
    branches:
      - main
    paths:
      - 'Team04/**/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: copy current branch name
      run: |
        bash
        current_branch = $(git rev-parse --abbrev-ref HEAD)
        echo $current_branch

    - name: Create a text file
      run: |
        echo "This is a test file." > Team04/testfile.txt

    - name: Push the text file
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add Team04/testfile.txt
        git commit -m "Add test text file"
        git push
