name: Push Text File Test

on:
  push:
    branches:
      - main
    paths:
      - 'Team04/**'

jobs:
  compare-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate diff file or handle single commit history
        run: |
          cd Team04
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            git diff HEAD~1 HEAD > diff.txt
          else
            echo "Not enough commits for a diff." > diff.txt
          fi

      - name: Display differences
        run: cat diff.txt

      - name: Commit and push changes
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add diff.txt
          git commit -m "Add differences between branches"
          git push