name: Push Text File Test

on:
  push:
    branches:
      - main
    paths:
      - 'Team04/**'

jobs:
  compare-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Compare branches
        run: |
          diff --recursive --ignore-submodules main current > differences.txt

      - name: Write differences to file
        run: |
          echo "Differences found:" >> differences.txt
          cat differences.txt

      - name: Clean up
        run: |
          rm differences.txt