name: Push Text File Test

on:
  push:
    branches:
      - main
    paths:
      - 'Team04/**'

jobs:
  compare-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install git
        run: sudo apt-get install git -y

      - name: Get list of changed files
        id: changed-files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main ${GITHUB_REF})
          echo "::set-output name=changed_files::${CHANGED_FILES}"

      - name: Write differences to file
        run: |
          echo "${{ steps.changed-files.outputs.changed_files }}" > differences.txt

      - name: Commit and push changes
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add differences.txt
          git commit -m "Add differences between branches"
          git push