name: Push Text File Test

on:
  push:
    branches:
      - main
    paths:
      - 'Team04/**'

jobs:
  compare-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install git
        run: sudo apt-get install git -y

      - name: copy current branch name
        run: |
          current_branch = $(git rev-parse --abbrev-ref HEAD)
          echo $current_branch

      - name: Get differences between branches
        id: diff
        run: |
          git fetch origin main
          git diff --name-status origin/main ${GITHUB_REF} > differences.txt || echo "No differences found"

      - name: Display differences
        run: cat differences.txt

      - name: Commit and push changes
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add differences.txt
          git commit -m "Add differences between branches"
          git push